#cloud-config
disable_root: true
timezone: Europe/Moscow
repo-update: true
repo-upgrade: true

users:
  - name: yc-user
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDHglT/JNX0P4hUv82eb47UrjhF35M2NzYOK+1LZ3vVRy/PEsk+uyBQwKEg6yJbEAxympKKdYfa8Xkm8VDO8HKdlCMOypjVMsUPOcmhKHJQWwqKYdf63TnHpeW0gwQmJlAkrXVvCQSj2Ttt6Ki1ai1Cu9AETe6jSVNZPq/B/jwr2Nnka0dNuY0+c9bbcKTJBcBmLFTAD1OFrEtmKL/57xfFDzKK0QBpNP+JsyqgXMRc7YK7ajOG5ITqcuvoByWJVHNouuQG+t76QcUjTj185q8URYBDawWLv4fEXRNd7Mrx1K0Pq/NY+6383b1VYuxtSOYGzIO3OWKY8PqrFoM012V7Oxg2hbMTeAhIypJQLNgVk38S5wjdwpb/UxI1KqnT1KHWSt6cR82IcegyuDCKgP0M+CTLz4Te0rZIdHfR9evEdpBVkFIRU8VdtuGPXWYXvSTBSKoNLlN0CVnTpTm9JMVyoUqENPvJZxWNbgKcmSkMrPFGKVHtdtdLCxF5QxXV6iM=

write_files:
 - path: /home/yc-user/startup_script.sh
   permissions: '0777'
   content: |
     #!/bin/bash
     sudo apt update
     sudo apt install -y ruby-full ruby-bundler build-essential
     sudo apt-get update
     sudo apt-get install apt-transport-https ca-certificates
     wget -qO - https://www.mongodb.org/static/pgp/server-4.2.asc | sudo apt-key add -
     echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.2.list
     sudo apt update
     sudo apt-get install -y mongodb-org
     sudo systemctl start mongod
     sudo systemctl enable mongod
     sudo apt-get install git --assume-yes
     git clone -b monolith https://github.com/express42/reddit.git
     cd reddit
     bundle install
     puma -d

runcmd:
 - [ /home/yc-user/startup_script.sh ]
